# 修改端口
server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  initance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 摘要信息
info:
  app.name: zuul-microcloud
  company.name: www.zuul.com
  build.artifactId: microservicecloud-zuul_gateway_9527
  build.version: 1.0-SNAPSHOT
# 更改网址访问服务名
zuul:
  routes:
    gateway.serviceId: springcloud
    gateway.path: /gateway/**
  # 设置原服务名不可用
  # ignored-services: springcloud
  # 加前缀
  prefix: /spring
  ignored-services: "*"
