# 声明端口号
server:
  port: 8081
# 开启用feign做负载均衡的功能
feign:
  hystrix:
    enabled: true
# 负载均衡，必须建立在集群
# 负载均衡必须是同一个网址访问到的不同的信息
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka