# 修改端口
server:
  port: 8002
# 加载映射文件
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 取别名
  type-aliases-package: com.os.springcloud.entities
  mapper-locations: mybatis/mapper/**/*.xml
# 微服务取名
spring:
  application:
    name: springcloud
  # 配置数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dept_02
    username: root
    password: 1314
# 客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: SpringCloud_8002 # 当前服务取别名
    prefer-ip-address: true # 显示IP地址
# 显示信息
info:
  app.name: SpringCloud_8002_provider
  company.name: com.provider.com
  build.artifactId: microservicecloud-provider_dept_8002
  build.version: 1.0-SNAPSHOT